# This is a basic workflow that is manually triggered

name: Scrape and parse
on:
  workflow_dispatch:
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'User ID'
        # Default value if no value is explicitly provided
        default: '1058225'
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: number

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7' # install the python version needed
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script
        run: python scraper.py
        env:
          userNameB: ${{secrets.MYTTUSERNAME}}
          userPassWordB: ${{secrets.MYTTPASSWORD}}
      - name: execute py script
        run: python extractData.py
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "imported files" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: main 
